### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by ghost** [mattegan/Love-Mandelbrot#1]
I get the following error when I attempt to run this using LÖVE2D 0.10.0:

Cannot compile pixel shader code:
Line 71: error: ambiguous overflowed function reference "log(int)"

Traceback:

[C]: in function 'newShader'
main.lua:55 in function 'load'
[C]: in function 'xpcall'

No idea why this is happening, though. I posted about this on the LÖVE2D forum post, but apparently it needs to be approved by a moderator.

**Comment by mattegan** [comment]
Fixed. GLSL doesn't support log on genITypes, and the fact that it worked on my platform is probably just an inconsistency. There will most likely be issues with the shader on other platforms as well.
